name: webpack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  webpack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          ssh-add - <<< "${{ secrets.KEY }}"
          
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - run: |
          npm i
          git clone --branch public --single-branch git@github.com:warden-sk/warden.git ./public
          node webpack
          cd public && git add . && git commit -m "update" && git push --force
