name: webpack

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - run: |
          npm i
          sudo git clone --branch public --single-branch git@github.com:warden-sk/warden.git ./public
          node webpack
          sudo cd ./public && git add . && git commit -m "update" && git push --force
